server:
  port: 8888

#thymeleaf设置
spring:
  thymeleaf:
    prefix: classpath:/templates/page/
    cache: false
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    #json对属性值为null 忽略
    default-property-inclusion: NON_NULL
  application:
    name: web-server

#eureka相关配置
eureka:
  instance:
    hostname: 127.0.0.1
  #修改eureka-client在注册中心页面显示的名字
  #${spring.cloud.client.ipaddress} 获取服务的ip地址
    instance-id: webService-${spring.cloud.client.ipaddress}-${server.port}
    #服务信息显示的真实的ip, 开发中一定要设置为true, 如果不设置, 其他电脑访问不到你的服务
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10001/eureka/


ribbon:
  eureka:
    enabled: true